# Generated by Django 4.1 on 2023-09-21 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='description',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='image',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='title',
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipe_desc',
            field=models.CharField(default='sjdfkljsadklf', max_length=200),
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipe_name',
            field=models.CharField(default='hello', max_length=200),
        ),
    ]
