# Generated by Django 4.1 on 2023-09-27 05:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FoodApp', '0004_recipe_recipe_img_alter_recipe_recipe_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='user_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
