# Generated by Django 4.1 on 2023-09-27 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodApp', '0005_recipe_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_desc',
            field=models.CharField(default='Recipe detail', max_length=10000),
        ),
    ]
