# Generated by Django 4.1 on 2023-09-27 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodApp', '0007_alter_recipe_recipe_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_desc',
            field=models.TextField(default='Recipe detail', max_length=1000),
        ),
    ]
