# Generated by Django 4.1 on 2023-09-24 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='https://cdn-icons-png.flaticon.com/512/3177/3177440.png', upload_to='profile_pictures'),
        ),
    ]
