# Generated by Django 4.1 on 2023-09-27 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='https://cpng.pikpng.com/pngl/s/326-3261783_person-icon-default-user-image-jpg-clipart.png', upload_to='profile_pictures'),
        ),
    ]
