# Generated by Django 4.1 on 2023-09-27 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='https://img.icons8.com/nolan/64/user-default.png', upload_to='profile_pictures'),
        ),
    ]
